(import (for-syntax :std/misc/ports))
(export #t)
(defsyntax (define-file stx)
  (syntax-case stx ()
    ((_ var filename)
     (stx-string? #'filename)
     (let* ((file (stx-e #'filename))
  	    (locat (stx-source stx))
            (con (##locat-container locat))
  	    (path (##container->path con))
  	    (dir (if path (path-directory path) (current-directory)))
  	    (u8v (read-file-u8vector (path-expand file dir))))
       (with-syntax ((f u8v))
	 #'(def var f))))))
